[versions]
wirespec = "0.0.0-SNAPSHOT"
jackson = "0.14.10"

[libraries]
wirespec_compiler = { module = "community.flock.wirespec.compiler:core-jvm", version.ref = "wirespec" }

[plugins]
wirespec = { id = "community.flock.wirespec.plugin.gradle", version.ref = "wirespec" }
