[versions]
wirespec = "0.15.2"
jackson = "2.19.0"

[libraries]
wirespec_compiler = { module = "community.flock.wirespec.compiler:core-jvm", version.ref = "wirespec" }

[plugins]
wirespec = { id = "community.flock.wirespec.plugin.gradle", version.ref = "wirespec" }
