name: Build pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
  release:
    types: [ "created" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-java:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build
        run: |
          ./gradlew :packages:java:build

  build-kotlin:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build
        run: |
          ./gradlew :packages:kotlin:build

  build-python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.9
          architecture: x64
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: generate
        run: |
          ./gradlew :packages:python:wirespec
      - name: install
        working-directory: packages/python
        run: |
          pip install -r requirements.txt
          pip install mypy
          pip install types-requests
      - name: mypy
        working-directory: packages/python
        run: |
          mypy .
      - name: test
        working-directory: packages/python/src
        run: |
          python -m unittest ./sdk_test.py
          python -m unittest ./signing_test.py

  build-npm:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install
        working-directory: packages/npm
        run: |
          npm install
      - name: generate
        working-directory: packages/npm
        run: |
          npm run generate
      - name: compile
        working-directory: packages/npm
        run: |
          npm run compile
      - name: test
        working-directory: packages/npm
        run: |
          npm test
